sudo: required
dist: trusty
language: generic
services:
- docker
env:
  matrix:
  - image='ubuntu-18-04-x64' type='lxd' root_user=root
  - image='ubuntu-18-04-x64' type='digitalocean' root_user=root
  - image='ubuntu-18-04-x64' type='travisssh' root_user=travis
  global:
  - COMMIT_AUTHOR_EMAIL: christian.wiedemann@key-tec.de
  - ENCRYPTION_LABEL: fe3d37fe6546

before_install:
- cd tests
- ./init-travis.sh $type $image
- cd ..
- ./bin/andock.sh _install-andock
- cd tests
- git clone https://github.com/andock/demo-project.git

script:
- bats server.bats
- bats build.bats
- bats fin.bats
