sudo: required
dist: trusty
language: php
php:
  - "7.1"
env:
  matrix:
  - image='ubuntu-18-04-x64' type='lxd'
  #- image='ubuntu-18-04-x64' type='digitalocean'
  global:
  - COMMIT_AUTHOR_EMAIL: christian.wiedemann@key-tec.de
  - ENCRYPTION_LABEL: fe3d37fe6546

before_install:
- cd tests
- ./init-travis.sh $type $image
- cd ..
- ./bin/andock.sh _install-andock
- cd tests
- git clone https://github.com/andock/demo-project.git

script:
- bats server.bats
- sudo lxc exec andock -- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo lxc exec andock -- sudo apt-get -qq update;
- sudo lxc exec andock -- sudo apt-get -y install docker-ce=17.10.0-ce
- bats build.bats
- bats fin.bats
