sudo: required
dist: xenial
language: generic
services:
  - docker
env:
  matrix:
    - ANDOCK_TEST_IMAGE='NO_IMAGE' ANDOCK_TEST_TYPE='travis' ANDOCK_ROOT_USER=travis ANDOCK_USER=travis ANDOCK_CONNECTION=local
    - ANDOCK_TEST_IMAGE='ubuntu-18-04-x64' ANDOCK_TEST_TYPE='digitalocean' ANDOCK_ROOT_USER=root ANDOCK_USER=andock ANDOCK_CONNECTION=default
  # - ANDOCK_TEST_IMAGE='ubuntu-18-04-x64' ANDOCK_TEST_TYPE='travisssh' ANDOCK_ROOT_USER=travis ANDOCK_CONNECTION=travisssh
  global:
    - COMMIT_AUTHOR_EMAIL: christian.wiedemann@key-tec.de
    - ENCRYPTION_LABEL: fe3d37fe6546

before_install:
  - cd tests
  - ./init-travis.sh $ANDOCK_TEST_TYPE $ANDOCK_TEST_IMAGE
  - cd ..
  - ./bin/andock.sh _install-andock
  - cd tests
  - git clone https://github.com/andock/test-project.git
  - git clone https://github.com/andock/boilerplate-drupal8.git
  - sudo curl -fsSL get.docksal.io | sh

script:
  - bats server.bats
  - bats build.bats
  - bats environment.bats

  # Install demo drupal.
  - if [ "${ANDOCK_TEST_TYPE}" = "digitalocean" ]; then cd boilerplate-drupal8; fin init; cd ..; bats drupal.bats; fi
#- curl -sL -I -k "https://www.master.demo-drupal.dev.andock.ci"
after_script:
  - ./cleanup-travis.sh $ANDOCK_TEST_TYPE $ANDOCK_TEST_IMAGE