sudo: required
dist: trusty
language: php
php:
  - "7.1"
services:
- docker
env:
  matrix:
  - image='ubuntu-18-04-x64' type='lxd'
  - image='ubuntu-18-04-x64' type='digital ocean'
  global:
  - COMMIT_AUTHOR_EMAIL: christian.wiedemann@key-tec.de
  - ENCRYPTION_LABEL: fe3d37fe6546

before_install:
- set -e
- cd tests
- ./init-travis.sh $type $image
- cd ..
- ./bin/andock.sh _install-andock
- cd tests
- git clone https://github.com/andock/demo-project.git

script:
- set -e
- bats server.bats
- bats build.bats
- bats fin.bats
