sudo: required
dist: trusty
language: generic
services:
- docker
env:
  matrix:
  # lxd is not working on travis.
  # - image='ubuntu-18-04-x64' type='lxd' ANDOCK_ROOT_USER=root ANDOCK_CONNECTION=default
  # - image='ubuntu-18-04-x64' type='digitalocean' ANDOCK_ROOT_USER=root ANDOCK_CONNECTION=default
  - test_image='ubuntu-18-04-x64' type='travisssh' ANDOCK_ROOT_USER=travis ANDOCK_CONNECTION=local
  # - image='ubuntu-18-04-x64' type='travisssh' ANDOCK_ROOT_USER=travis ANDOCK_CONNECTION=travisssh
  global:
  - COMMIT_AUTHOR_EMAIL: christian.wiedemann@key-tec.de
  - ENCRYPTION_LABEL: fe3d37fe6546

before_install:
- cd tests
- ./init-travis.sh $type $test_image
- cd ..
- ./bin/andock.sh _install-andock
- cd tests
- git clone https://github.com/andock/demo-project.git

script:
- bats server.bats
- cd demo-project
- ../../bin/andock.sh "@${ANDOCK_CONNECTION}" build -e "branch=master"
- bats build.bats
- bats fin.bats
