namespace: "andock"
name: "andock"
version: "1.1.0"
readme: "README.md"
authors:
  - "Christian Wiedemann <christian.wiedemann@key-tec.de>"
license:
  - "MIT"
tags:
  - docksal
repository: "https://www.github.com/andock/andock"