site_name: andock documentation
theme: readthedocs
repo_url: https://github.com/andock/andock
site_url: https://docs.andock
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Home: index.md
  - Big Picture:
    - Introduction: big-picture/introduction.md
  - Getting started:
    - System requirements: getting-started/system-requirements.md
    - 5 minutes setup: getting-started/docksal.md
  - Configuration:
    - andock.yml: configuration/andock.md
    - Build: configuration/build.md
    - Fin: configuration/fin.md
    - Let's Encrypt: configuration/letsencrypt.md
    - Hook configurations:
      - Drupal: configuration/example-drupal-hooks.md
  - Integrations:
    - CI: integrations/ci.md