site_name: andock documentation
theme: readthedocs
repo_url: https://github.com/andock/andock
site_url: https://docs.andock
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Home: index.md
  - Getting started:
    - Introduction: getting-started/introduction.md
    - System requirements: getting-started/system-requirements.md
    - 5 minutes setup: getting-started/docksal.md
      - Test with Vagrant:  getting-started/vagrant.md
      - Test Andock on a Cloud Box:  getting-started/cloud.md
  - Configuration:
    - Basic configuration: configuration/andock.md
    - Hooks: configuration/hooks.md
    - Connections: configuration/connections.md
    - Build: configuration/build.md
    - Environments: configuration/environment.md
    - Let's Encrypt: configuration/letsencrypt.md
    - Redirects: configuration/redirects.md

  - Integrations:
    - CI: integrations/ci.md
    - Drush: integrations/drush.md
    - Notfication: integrations/notifications.md